#documentation 📝:
#  - any: ["docs/**/*.md", "i18n/**/docusaurus-plugin-content-docs/**"]
#dependencies 📦:
#  - any: ["package.json", "yarn.lock"]
#enhancement ✨:
#  - any: [".prettierrc", ".prettierignore", ".markdownlint.json", "tsconfig.json"]
#maintenance 📈:
#  - any: [".github/CODEOWNERS", ".github/*.md", ".github/*.yml", ".github/*.json"]
#i18n 🌐:
#  - any: ["i18n/**"]
#annex 💠:
#  - any: ["docs/ecosystem/annexes/**", "i18n/**/docusaurus-plugin-content-docs/current/ecosystem/annexes/*"]
#package 📦:
#  - any: ["docs/ecosystem/packages*", "i18n/**/docusaurus-plugin-content-docs/current/ecosystem/packages/*"]
#plugin 🧿:
#  - any: ["docs/ecosystem/plugins/**", "i18n/**/docusaurus-plugin-content-docs/current/ecosystem/plugins/*"]
#ci 🤖:
blocked 🛑:
  - any: ["profile-summary-card-output/**"]
