#!/bin/bash
set -e
###
###
echo "Creating common folders in correct language"
xdg-user-dirs-update
xdg-user-dirs-update --force

echo "Creating private folders we use later"

[ -d $HOME"/.bin" ] || mkdir -p $HOME"/.bin"
[ -d $HOME"/.fonts" ] || mkdir -p $HOME"/.fonts"
[ -d $HOME"/.icons" ] || mkdir -p $HOME"/.icons"
[ -d $HOME"/.themes" ] || mkdir -p $HOME"/.themes"
[ -d $HOME"/.local/share/icons" ] || mkdir -p $HOME"/.local/share/icons"
[ -d $HOME"/.local/share/themes" ] || mkdir -p $HOME"/.local/share/themes"

echo "Creating personal folders"

[ -d $HOME"/REP" ] || mkdir -p $HOME"/REP"
[ -d $HOME"/REP/SSrep" ] || mkdir -p $HOME"/REP/SSrep"
[ -d $HOME"/REP/linux" ] || mkdir -p $HOME"/REP/linux"
[ -d $HOME"/Public/SS" ] || mkdir -p $HOME"/Public/SS"
[ -d $HOME"/" ] || mkdir -p $HOME"/Insync"

echo "Installing .bashrc-personal"

installed_dir=$(dirname $(readlink -f $(basename `pwd`)))

cp $installed_dir/settings/shell-personal/.bashrc-personal ~
cp $installed_dir/settings/shell-personal/.zshrc-personal ~

echo "Installing personal settings of variety"

cp $installed_dir/settings/variety/variety.conf ~/.config/variety/

echo "Installing screenkey for teaching"

cp $installed_dir/settings/screenkey/screenkey.json ~/.config/

#echo "copy/paste wallpapers to variety"
# DIR=$HOME"/.config/variety/Favorites/"
# echo $DIR
# if [ -d "$DIR" ]; then
#   # Take action if $DIR exists. #
#   echo "Copying files to ${DIR}..."
#   cp ~/Dropbox/Apps/Desktoppr/* ~/.config/variety/Favorites/
# fi

echo "################################################################"
echo "#########            Folders created            ################"
echo "################################################################"

