#!/bin/bash
#set -e

##################################################################################################################

#bookmarks

installed_dir=$(dirname $(readlink -f $(basename `pwd`)))
cp $installed_dir/settings/plasma/bookmarks/user-places.xbel ~/.local/share/user-places.xbel


echo "################################################################"
echo "####                 PLASMA  INSTALLED                    ######"
echo "################################################################"
