#!/bin/bash
set -e
##################################################################################################################

FIND='#PACKAGER="John Doe <john@doe.com>"'
REPLACE='PACKAGER="Salvydas Lukosius <sall@w-ss.io>"'

find /etc/makepkg.conf -type f -exec sudo sed -i "s/$FIND/$REPLACE/g" {} \;

echo "################################################################"
echo "####                     MakePkg corrected                ######"
echo "################################################################"
