---
name: 🚀 Publish assets

on:
  push:
    branches:
      - assets # Set a branch name to trigger deployment
    paths:
      - "*.svg"
  workflow_run:
    workflows:
      - 🌀 SSO
      - 🌀 SPOTIFY
    types: [completed]
  workflow_dispatch: {}

permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    timeout-minutes: 15
    permissions:
      deployments: write
      pages: write
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: 🚀 Deploy metrics
        if: github.ref == 'refs/heads/assets'
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: assets
          publish_dir: .
          user_name: ${{ secrets.ACTIONS_USER }}
          user_email: ${{ secrets.ACTIONS_MAIL }}
          keep_files: true
