---
name: "🌀 GHM"

on:
  workflow_dispatch:
  schedule:
    - cron: "30 10 * * *"

jobs:
  github-metrics:
    name: ♻️ Update Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SSO_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
