name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Recent activity
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.activity.svg
        token: ${{ secrets.GH_PAT }}
        base: ""
        plugin_activity: yes
        plugin_activity_limit: 5
        plugin_activity_days: 0
        plugin_activity_filter: issue, pr, release, review, ref/create
    - name: Indepth analysis
      uses: ss-o/metrics@latest
      with:
        filename: metrics/plugin.notable.indepth.svg
        token: ${{ secrets.GH_PAT }}
        base: ""
        plugin_notable: yes
        plugin_notable_indepth: yes
        plugin_notable_repositories: yes
    - name: Spotify - Random track from playlist
      uses: lowlighter/metrics@latest
      with:
        filename: metrics/plugin.music.playlist2.spotify.svg
        token: NOT_NEEDED
        base: ""
        plugin_music: yes
        plugin_music_playlist: https://open.spotify.com/playlist/2MvEUsMh1eGSrezcirrXFd
    - name: Spotify - Random track from playlist
      uses: lowlighter/metrics@latest
      with:
        filename: metrics/plugin.music.playlist.spotify.svg
        token: NOT_NEEDED
        base: ""
        plugin_music: yes
        plugin_music_playlist: https://open.spotify.com/playlist/0vvXsWCC9xrXsKd4FyS8kM?si=37926df002064d19
        
        name: Spotify - Recently listed
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.music.recent.svg
        token: NOT_NEEDED
        base: ""
        plugin_music: yes
        plugin_music_provider: spotify
        plugin_music_mode: recent
        plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
        plugin_music_limit: 2
    - name: Spotify - Top tracks
      uses: lowlighter/metrics@latest
      with:
        token: NOT_NEEDED
        base: ""
        plugin_music: yes
        plugin_music_mode: top
        plugin_music_provider: spotify
        plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
        plugin_music_time_range: short
        plugin_music_top_type: tracks
