---
name: "🌀 SPOTIFY"
on:
  workflow_dispatch:
  schedule:
    - cron: "20 20 * * */2"
  push:
    paths: [.github/workflows/spotify.yml]
jobs:
  get-random-songs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/plugin/music/spotify/playlist/west.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_playlist: https://open.spotify.com/embed/playlist/2MvEUsMh1eGSrezcirrXFd
          plugin_music_limit: 2
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/plugin/music/spotify/playlist/east.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_playlist: https://open.spotify.com/embed/playlist/1X0xAsHWCpamURi0SJqV3w
          plugin_music_limit: 2
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/plugin/music/spotify/playlist/girls.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_playlist: https://open.spotify.com/embed/playlist/0CXloQmqFutohB4QMcgIq1 
          plugin_music_limit: 2
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/plugin/music/spotify/playlist/lofi-1.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_playlist: https://open.spotify.com/embed/playlist/6VcZq5Pm10ZTKp8SeLrp6G
          plugin_music_limit: 2
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/plugin/music/spotify/playlist/lofi-2.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_playlist: https://open.spotify.com/embed/playlist/290lnDXzAXbDqZhnfdJuYf
          plugin_music_limit: 2
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/plugin/music/spotify/playlist/lofi-3.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_playlist: https://open.spotify.com/embed/playlist/154SEnZOkJqFJlSNIPzyU5
          plugin_music_limit: 2
  get-recent-music:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/plugin/music/spotify/recent.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_limit: 4
  get-top-tacks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/plugin/music/spotify/top-tracks.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: short
          plugin_music_top_type: tracks
  get-top-artists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/plugin/music/spotify/top-artists.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: long
          plugin_music_top_type: artists
