---
name: "🌀 SPOTIFY"
on:
  schedule:
    - cron: "20 20 * * */2"
  push:
    branches: [main]
    paths: [.github/workflows/spotify.yml]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  recent_svg: metrics/plugin/music/spotify/recent.svg
  top_tracks_svg: metrics/plugin/music/spotify/top-tracks.svg
  top_artists_svg: metrics/plugin/music/spotify/top-artists.svg
  playlist_lofi: https://open.spotify.com/embed/playlist/0vvXsWCC9xrXsKd4FyS8kM
  playlist_lofi_svg: metrics/plugin/music/spotify/lofi.svg
  playlist_girls: https://open.spotify.com/embed/playlists/0CXloQmqFutohB4QMcgIq1
  playlist_girls_svg: metrics/plugin/music/spotify/girls.svg
  playlist_east: https://open.spotify.com/embed/1X0xAsHWCpamURi0SJqV3w
  playlist_east_svg: metrics/plugin/music/spotify/east.svg
  playlist_west: https://open.spotify.com/embed/playlist/2MvEUsMh1eGSrezcirrXFd
  playlist_west_svg: metrics/plugin/music/spotify/west.svg

jobs:
  spotify-metrics:
    environment: metrics
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@f99da6c94154d2a35384b004b2cfbd7cc83830b9
        with:
          filename: ${{ env.playlist_west_svg }}
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_playlist: ${{ env.playlist_west_svg }}
          plugin_music_limit: 2
      - uses: lowlighter/metrics@f99da6c94154d2a35384b004b2cfbd7cc83830b9
        with:
          filename: ${{ env.playlist_east_svg }}
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_playlist: ${{ env.playlist_east }}
          plugin_music_limit: 2
      - uses: lowlighter/metrics@f99da6c94154d2a35384b004b2cfbd7cc83830b9
        with:
          filename: ${{ env.playlist_girls_svg }}
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_playlist: ${{ env.playlist_girls }}
          plugin_music_limit: 2
      - uses: lowlighter/metrics@f99da6c94154d2a35384b004b2cfbd7cc83830b9
        with:
          filename: ${{ env.playlist_lofi_svg }}
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_playlist: ${{ env.playlist_lofi }}
          plugin_music_limit: 2
      - uses: lowlighter/metrics@f99da6c94154d2a35384b004b2cfbd7cc83830b9
        with:
          filename: ${{ env.recent_svg }}
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_limit: 2
      - uses: lowlighter/metrics@f99da6c94154d2a35384b004b2cfbd7cc83830b9
        with:
          filename: ${{ env.top_tracks_svg }}
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_limit: 2
      - uses: lowlighter/metrics@f99da6c94154d2a35384b004b2cfbd7cc83830b9
        with:
          filename: ${{ env.top_artists_svg }}
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: long
          plugin_music_top_type: artists
          plugin_music_limit: 2
