---
name: 🌀 SPOTIFY
on:
  schedule:
    - cron: 20 20 * * */2
  push:
    branches: [main]
    paths: [.github/workflows/spotify.yml]
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

env:
  recent_svg: metrics/spotify/recent.svg
  top_tracks_svg: metrics/spotify/top-tracks.svg
  top_artists_svg: metrics/spotify/top-artists.svg
  playlist_lofi: https://open.spotify.com/embed/playlist/2HR2xejzf2rJ1e7q0rBBcC
  commit_branch: gh-pages
  
jobs:
  spotify-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      pages: write
      id-token: write
    timeout-minutes: 30
    environment: metrics
    if: github.repository == 'ss-o/ss-o'
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          committer_branch: ${{ env.commit_branch }}    
          filename: ${{ env.recent_svg }}
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_played_at: false
          plugin_music_time_range: short
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_limit: 2
          
      - uses: lowlighter/metrics@v3.34
        with:
          committer_branch: ${{ env.commit_branch }}       
          filename: ${{ env.top_tracks_svg }}
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_limit: 2
          
      - uses: lowlighter/metrics@v3.34
        with:
          committer_branch: ${{ env.commit_branch }}            
          filename: ${{ env.top_artists_svg }}
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: month
          plugin_music_top_type: artists
          plugin_music_limit: 4
