---
name: "🌀 SSO"
on:
  schedule:
    - cron: "09 09 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths: [.github/workflows/sso.yml]

env:
  metrics_svg: metrics/plugin/metrics.svg
  followup_svg: metrics/plugin/followup-indepth.svg
  topics_icons_svg: metrics/plugin/topics-icons.svg
  languages_details_svg: metrics/plugin/languages-details.svg
  starlists_languages_svg: metrics/plugin/starlists-languages.svg
  snake_svg: metrics/plugin/snake.svg
  snake_dark_svg: metrics/plugin/snake-dark.svg?palette=github-dark
  z_shell_stargazers_svg: metrics/plugin/stargazers.svg
  discussions_svg: metrics/plugin/discussions.svg
  reactions_svg: metrics/plugin/reactions.svg
  wakatime_svg: metrics/plugin/wakatime.svg
  GITHUB_TOKEN: ${{ secrets.SSO_TOKEN }}

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: metrics
    concurrency:
      group: ci-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@c1240845bc6547ad60bfcf8d26838c82be83d573
        with:
          filename: ${{ env.metrics_svg }}
          token: ${{ secrets.SSO_TOKEN }}
          user: ${{ github.repository_owner }}
          base: header, activity,community,repositories
          base_indepth: yes
      - uses: lowlighter/metrics@c1240845bc6547ad60bfcf8d26838c82be83d573
        with:
          filename: ${{ env.followup_svg }}
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          user: ${{ github.repository_owner }}
          plugin_followup: yes
          plugin_followup_indepth: yes
      - uses: lowlighter/metrics@c1240845bc6547ad60bfcf8d26838c82be83d573
        with:
          filename: ${{ env.z_shell_stargazers_svg }}
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          plugin_stargazers: yes
          user: z-shell
      - uses: lowlighter/metrics@c1240845bc6547ad60bfcf8d26838c82be83d573
        with:
          filename: ${{ env.topics_icons_svg }}
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
      - uses: lowlighter/metrics@c1240845bc6547ad60bfcf8d26838c82be83d573
        with:
          filename: ${{ env.languages_details_svg }}
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, handlebars, gnuplot, scss, sass, makefile, lua
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6
      - uses: Platane/snk@29c7ee48ec6ea2fe6e15abec3a9f812a2bebcd69
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ${{ env.snake_svg }}
            ${{ env.snake_dark_svg }}
      - if: success()
        uses: crazy-max/ghaction-github-pages@c0d7ff0487ee0415efb7f32dab10ea880330b1dd
        with:
          author: ${{ secrets.ACTIONS_USER }} <${{ secrets.ACTIONS_MAIL }}>
          committer: ${{ secrets.ACTIONS_USER }} <${{ secrets.ACTIONS_MAIL }}>
          target_branch: gh-pages
          build_dir: metrics
          keep_history: true
      - uses: lowlighter/metrics@c1240845bc6547ad60bfcf8d26838c82be83d573
        with:
          filename: ${{ env.wakatime_svg }}
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_days: 30
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
      - uses: lowlighter/metrics@c1240845bc6547ad60bfcf8d26838c82be83d573
        with:
          filename: ${{ env.discussions_svg }}
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          plugin_discussions: yes
          plugin_discussions_categories: no
          plugin_discussions_categories_limit: 8
      - uses: lowlighter/metrics@c1240845bc6547ad60bfcf8d26838c82be83d573
        with:
          filename: ${{ env.reactions_svg }}
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_details: percentage
      #- uses: lowlighter/metrics@c1240845bc6547ad60bfcf8d26838c82be83d573
      #with:
      #    filename: ${{ env.starlists_languages_svg }}
      #    token: NOT_NEEDED
      #    base: ""
      #    plugin_starlists: yes
      #    plugin_starlists_languages: yes
      #    plugin_starlists_limit_languages: 2
      #    plugin_starlists_limit_repositories: 2
