---
name: "🌀 SSO"
on:
  schedule:
    - cron: "09 09 * * *"
  workflow_dispatch:
  push:
    paths: [.github/workflows/sso.yml]
  pull_request:
    paths: [.github/workflows/sso.yml]
  
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@58025c0755c249c0a7c0ed5d8f5b8848e1bfb374
        with:
          filename: metrics/plugin.svg
          token: ${{ secrets.SSO_TOKEN }}
          user: ss-o
      - uses: lowlighter/metrics@58025c0755c249c0a7c0ed5d8f5b8848e1bfb374
        with:
          filename: metrics/plugin/followup/indepth.svg
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          user: ss-o
          plugin_followup: yes
          plugin_followup_indepth: yes
      - uses: lowlighter/metrics@58025c0755c249c0a7c0ed5d8f5b8848e1bfb374
        with:
          filename: metrics/plugin/gists.svg
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          plugin_gists: yes
      - uses: lowlighter/metrics@58025c0755c249c0a7c0ed5d8f5b8848e1bfb374
        with:
          filename: metrics/plugin/topics/icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
      - uses: lowlighter/metrics@58025c0755c249c0a7c0ed5d8f5b8848e1bfb374
        with:
          filename: metrics/plugin/languages/details.svg
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, handlebars, gnuplot, scss, sass, makefile
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
      - uses: lowlighter/metrics@58025c0755c249c0a7c0ed5d8f5b8848e1bfb374
        with:
          filename: metrics/plugin/introduction.svg
          token: ${{ secrets.SSO_TOKEN }}
          user: ss-o
          base: header
          plugin_introduction: yes
      - uses: lowlighter/metrics@58025c0755c249c0a7c0ed5d8f5b8848e1bfb374
        with:  
          filename: metrics/plugin/support.svg
          token: NOT_NEEDED
          base: ""
          plugin_support: yes
  snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@d078b2d231ad307c3e5efe7a3e0d630141ce54a8
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: metrics/grid-snake.gif
          svg_out_path: metrics/grid-snake.svg
#      - uses: crazy-max/ghaction-github-pages@11b007c0cdea034121c8d2020fdf0dbf79d371d5
#        with:
#          committer: Digital Teams <digital-teams@pm.me>
#          target_branch: out
#          build_dir: metrics
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
