---
name: "🌀 SSO"
on:
  schedule:
    - cron: "09 09 * * *"
  workflow_dispatch:
  push:
    paths: [.github/workflows/sso.yml]
  pull_request:
    paths: [.github/workflows/sso.yml]

jobs:
  run-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: metrics/plugin.svg
          token: ${{ secrets.SSO_TOKEN }}
          user: ${{ github.repository_owner }}
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: metrics/plugin/habits/charts.svg
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: ${{ secrets.TIMEZONE }}
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: metrics/plugin/stargazers.svg
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          plugin_stargazers: yes
          user: z-shell
  run-2:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: metrics/plugin/followup/indepth.svg
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          user: ${{ github.repository_owner }}
          plugin_followup: yes
          plugin_followup_indepth: yes
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: metrics/plugin/topics/icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: metrics/plugin/languages/details.svg
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, handlebars, gnuplot, scss, sass, makefile, lua
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: metrics/plugin/achievements.svg
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, developer, manager
            scripter, packager, infographile
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
  run-3:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: metrics/plugin/support.svg
          token: NOT_NEEDED
          base: ""
          user: ${{ github.repository_owner }}
          plugin_support: yes
      - uses: Platane/snk@d078b2d231ad307c3e5efe7a3e0d630141ce54a8
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            metrics/snake.svg
            metrics/snake-dark.svg?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@eb08c35b9fab86751edfff4e55cd5cde35ff0e52
        with:
          committer: Digital Teams <digital-teams@pm.me>
          target_branch: snake
          build_dir: metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-4:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: metrics/plugin/wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: metrics/plugin/reactions.svg
          token: ${{ secrets.SSO_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 500
          plugin_reactions_details: percentage
