---
name: "🌀 SSO"

on:
  schedule:
    - cron: '09 09 * * *'
  workflow_dispatch:
    
jobs:
  sso-metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ss-o/metrics@latest
      with:
        filename: metrics/plugin.svg
        token: ${{ secrets.SSO_TOKEN }}
        user: ss-o
    - uses: /metrics@latest
      with:
        filename: metrics/plugin.followup.indepth.svg
        token: ${{ secrets.SSO_TOKEN }}
        base: ""
        user: ss-o
        plugin_followup: yes
        plugin_followup_indepth: yes
#    - name: Spotify - Random track from playlist
#      uses: ss-o/metrics@latest
#      with:
#        filename: metrics/plugin.music.playlist2.spotify.svg
#        token: NOT_NEEDED
#        base: ""
#        plugin_music: yes
#        plugin_music_playlist: https://open.spotify.com/playlist/2MvEUsMh1eGSrezcirrXFd
#    - name: Spotify - Random track from playlist
#      uses: ss-o/metrics@latest
#      with:
#        filename: metrics/plugin.music.playlist.spotify.svg
#        token: NOT_NEEDED
#        base: ""
#        plugin_music: yes
#        plugin_music_playlist: https://open.spotify.com/playlist/0vvXsWCC9xrXsKd4FyS8kM?si=37926df002064d19        
#    - name: Spotify - Recently listed
#    - uses: ss-o/metrics@latest
#      with:
#        filename: metrics.plugin.music.recent.svg
#        token: NOT_NEEDED
#        base: ""
#        plugin_music: yes
#        plugin_music_provider: spotify
#        plugin_music_mode: recent
#        plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
#        plugin_music_limit: 2
#    - name: Spotify - Top tracks
#      uses: ss-o/metrics@latest
#      with:
#        token: NOT_NEEDED
#        base: ""
#        plugin_music: yes
#        plugin_music_mode: top
#        plugin_music_provider: spotify
#        plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
#        plugin_music_time_range: short
#        plugin_music_top_type: tracks
