---
name: "⭕ Trunk [cache]"
on:
  push:
    paths: [.trunk/trunk.yaml]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: write-all

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v3
      - name: ✨ Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: populate_cache_only
