name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: False
          SHOW_LINES_OF_CODE: True
          SHOW_OS: True
          SHOW_PROJECTS: True
          SHOW_EDITORS: True
          SHOW_TIMEZONE: True
          SHOW_COMMIT: True
          SHOW_LANGUAGE: True
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_DAYS_OF_WEEK: True
          HOW_PROFILE_VIEWS: True
          SHOW_SHORT_INFO: True
          LOCALE: en
          COMMIT_BY_ME: False
