name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: waka-box
        uses: matchai/waka-box@v4.0.5
      - name: wakatime-sync
        uses: superman66/wakatime-sync@v1.0.0
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: False
          SHOW_LINES_OF_CODE: True
      - name: Profile Readme
        uses: actions-js/profile-readme@v1
        with:
         github_token: ${{ secrets.GH_TOKEN }}
         username: ss-o
